[versions]
#jetbrains
geocoderVersion = "3.21"
kotlin = "2.3.0"
kotlinxSerializationJson = "1.9.0"
#KSP
ksp = "2.3.4"
#Detekt
detekt = "1.23.8"
detektCompose = "0.4.28"
#AndroidX
androidx-constraintlayout = "2.2.1"
androidx-swiperefreshlayout = "1.2.0"
androidx-lifecycleprocess = "2.10.0"
androidx-documentfile = "1.1.0"
#Eventbus
eventbus = "3.3.1"
#Room
room = "2.8.4"
#Fossify
commons = "5.13.1"
mmslib = "1.0.0"
indicator-fast-scroll = "4524cd0b61"
#Gradle
gradlePlugins-agp = "9.0.0"
#Helpers
ez-vcard = "0.12.1"
#Other
autofitTextView = "0.2.1"
libphonenumberVersion = "9.0.21"
libphonenumberinfo = "c77bdd2b69"
okhttp = "4.12.0"
slf4j = "1.7.36"
work = "2.9.0"
bouncycastle = "1.78.1"
msgpack = "0.9.11"
#build
app-build-compileSDKVersion = "36"
app-build-targetSDK = "36"
app-build-minimumSDK = "26"
app-build-javaVersion = "VERSION_17"
app-build-kotlinJVMTarget = "17"

[libraries]
#AndroidX
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-lifecycleprocess" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "androidx-documentfile" }
#Room
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
#Compose
compose-detekt = { module = "io.nlopez.compose.rules:detekt", version.ref = "detektCompose" }
#Fossify
fossify-commons = { module = "org.fossify:commons", version.ref = "commons" }
indicator-fast-scroll = { module = "org.fossify:IndicatorFastScroll", version.ref = "indicator-fast-scroll" }
mmslib = { module = "org.fossify:mmslib", version.ref = "mmslib" }
#EventBus
eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbus" }
#Kotlin
geocoder = { module = "com.googlecode.libphonenumber:geocoder", version.ref = "geocoderVersion" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
#Helpers
ez-vcard = { module = "com.googlecode.ez-vcard:ez-vcard", version.ref = "ez-vcard" }
#Other
autofit-text-view = { module = "me.grantland:autofittextview", version.ref = "autofitTextView" }
libphonenumber = { module = "com.googlecode.libphonenumber:libphonenumber", version.ref = "libphonenumberVersion" }
libphonenumberinfo = { module = "com.gitlab.xynngh:LibPhoneNumberInfo", version.ref = "libphonenumberinfo" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
slf4j-android = { module = "org.slf4j:slf4j-android", version.ref = "slf4j" }
work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
bouncycastle = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }
msgpack-core = { module = "org.msgpack:msgpack-core", version.ref = "msgpack" }

[bundles]
room = [
    "androidx-room-ktx",
    "androidx-room-runtime",
]

[plugins]
android = { id = "com.android.application", version.ref = "gradlePlugins-agp" }
androidLibrary = { id = "com.android.library", version.ref = "gradlePlugins-agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
