default_platform(:android)

platform :android do
  desc 'Run unit & instrumentation tests'
  lane(:test) { test_android }

  desc 'Build release artifacts'
  lane(:deploy) { deploy_android }

  desc 'Process app-store metadata'
  lane(:metadata) { metadata_android }
end
